"""initial schema

Revision ID: 9e648ad2e49f
Revises: 
Create Date: 2026-09-10 16:14:11.554274
"""
from alembic import op
import sqlalchemy as sa


revision = '9e648ad2e49f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('llm_response_id', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_project_id'), ['project_id'], unique=False)

    op.create_table('confirmations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('action_label', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confirmations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confirmations_status'), ['status'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('report_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('active_revision_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('store_name', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vector_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vector_records_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vector_records_store_name'), ['store_name'], unique=False)
        batch_op.create_index('ix_vector_store_ref', ['store_name', 'ref_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('revision_a_id', sa.String(length=64), nullable=False),
    sa.Column('revision_b_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_revision_a_id'), ['revision_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_revision_b_id'), ['revision_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_status'), ['status'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_json', sa.JSON(), nullable=False),
    sa.Column('tool_calls_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('pending_confirmation_id', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('components',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('subsystem', sa.String(length=64), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=False),
    sa.Column('weight_g', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_project_id'), ['project_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('doc_revision', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('authority', sa.String(length=64), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_title'), ['title'], unique=False)

    op.create_table('evaluation_metrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('evaluation_run_id', sa.String(length=64), nullable=False),
    sa.Column('subset', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_eval_metric', ['evaluation_run_id', 'subset', 'metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_metrics_evaluation_run_id'), ['evaluation_run_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=True),
    sa.Column('component_id', sa.String(length=64), nullable=True),
    sa.Column('analysis_run_id', sa.String(length=64), nullable=True),
    sa.Column('change_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_revision_id'), ['revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parent_revision_id', sa.String(length=64), nullable=True),
    sa.Column('released_by', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revisions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_revisions_project_id'), ['project_id'], unique=False)

    op.create_table('analysis_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=400), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_events_analysis_run_id'), ['analysis_run_id'], unique=False)

    op.create_table('changes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('revision_a_id', sa.String(length=64), nullable=False),
    sa.Column('revision_b_id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=True),
    sa.Column('drawing_id', sa.String(length=64), nullable=True),
    sa.Column('change_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('old_value', sa.String(length=300), nullable=True),
    sa.Column('new_value', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('location_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('detection_method', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.create_index('ix_change_run_component', ['analysis_run_id', 'component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_changes_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_changes_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_changes_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_changes_project_id'), ['project_id'], unique=False)

    op.create_table('component_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('properties_json', sa.JSON(), nullable=False),
    sa.Column('changed_from_parent', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'revision_id', name='uq_component_revision')
    )
    with op.batch_alter_table('component_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_revisions_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_component_revisions_revision_id'), ['revision_id'], unique=False)

    op.create_table('dependencies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_component_id', sa.String(length=64), nullable=False),
    sa.Column('target_component_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_component_id', 'target_component_id', 'relationship_type', name='uq_dep')
    )
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.create_index('ix_dep_target', ['target_component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependencies_project_id'), ['project_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=True),
    sa.Column('revision_id', sa.String(length=64), nullable=True),
    sa.Column('bbox_json', sa.JSON(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_doc_component', ['document_id', 'component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_revision_id'), ['revision_id'], unique=False)

    op.create_table('drawings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('drawing_type', sa.String(length=64), nullable=False),
    sa.Column('sheet', sa.String(length=32), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('manifest_path', sa.String(length=512), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drawings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drawings_revision_id'), ['revision_id'], unique=False)

    op.create_table('finding_components',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'component_id', name='uq_finding_component')
    )
    with op.batch_alter_table('finding_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_components_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_components_finding_id'), ['finding_id'], unique=False)

    op.create_table('finding_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('chunk_id', sa.String(length=64), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('bbox_json', sa.JSON(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_evidence_finding_id'), ['finding_id'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('requirement_type', sa.String(length=48), nullable=False),
    sa.Column('applies_to_json', sa.JSON(), nullable=False),
    sa.Column('normative', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_project_id'), ['project_id'], unique=False)

    op.create_table('tool_executions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=64), nullable=True),
    sa.Column('chat_session_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('mutating', sa.Boolean(), nullable=False),
    sa.Column('confirmation_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_executions_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_tool_name'), ['tool_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_executions_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_chat_session_id'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_analysis_run_id'))

    op.drop_table('tool_executions')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_project_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_document_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_code'))

    op.drop_table('requirements')
    with op.batch_alter_table('finding_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_evidence_finding_id'))

    op.drop_table('finding_evidence')
    with op.batch_alter_table('finding_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_components_finding_id'))
        batch_op.drop_index(batch_op.f('ix_finding_components_component_id'))

    op.drop_table('finding_components')
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawings_revision_id'))
        batch_op.drop_index(batch_op.f('ix_drawings_project_id'))

    op.drop_table('drawings')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_revision_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_component_id'))
        batch_op.drop_index('ix_chunk_doc_component')

    op.drop_table('document_chunks')
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependencies_project_id'))
        batch_op.drop_index('ix_dep_target')

    op.drop_table('dependencies')
    with op.batch_alter_table('component_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_revisions_revision_id'))
        batch_op.drop_index(batch_op.f('ix_component_revisions_component_id'))

    op.drop_table('component_revisions')
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changes_project_id'))
        batch_op.drop_index(batch_op.f('ix_changes_component_id'))
        batch_op.drop_index(batch_op.f('ix_changes_change_type'))
        batch_op.drop_index(batch_op.f('ix_changes_analysis_run_id'))
        batch_op.drop_index('ix_change_run_component')

    op.drop_table('changes')
    with op.batch_alter_table('analysis_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_events_analysis_run_id'))

    op.drop_table('analysis_events')
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revisions_project_id'))
        batch_op.drop_index(batch_op.f('ix_revisions_name'))

    op.drop_table('revisions')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_revision_id'))
        batch_op.drop_index(batch_op.f('ix_findings_project_id'))
        batch_op.drop_index(batch_op.f('ix_findings_component_id'))
        batch_op.drop_index(batch_op.f('ix_findings_analysis_run_id'))

    op.drop_table('findings')
    with op.batch_alter_table('evaluation_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_metrics_evaluation_run_id'))
        batch_op.drop_index('ix_eval_metric')

    op.drop_table('evaluation_metrics')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_title'))
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))

    op.drop_table('documents')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_components_project_id'))
        batch_op.drop_index(batch_op.f('ix_components_name'))

    op.drop_table('components')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_revision_b_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_revision_a_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_project_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('vector_records', schema=None) as batch_op:
        batch_op.drop_index('ix_vector_store_ref')
        batch_op.drop_index(batch_op.f('ix_vector_records_store_name'))
        batch_op.drop_index(batch_op.f('ix_vector_records_ref_id'))

    op.drop_table('vector_records')
    op.drop_table('users')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    op.drop_table('evaluation_runs')
    with op.batch_alter_table('confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confirmations_status'))
        batch_op.drop_index(batch_op.f('ix_confirmations_project_id'))

    op.drop_table('confirmations')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_project_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_events')
    # ### end Alembic commands ###
